### ISSUE TITLE
Incorrect boolean validation

### ISSUE THREAD

**Issue by olegrok** [tarantool/graphql#14]
```lua
tarantool> require('graphql.parse').parse('{ a(arg: False) }')
---
- definitions:
  - operation: query
    selectionSet:
      selections:
      - arguments:
        - kind: argument
          name:
            kind: name
            value: arg
          value:
            kind: enum
            value: False
        name:
          kind: name
          value: a
        kind: field
      kind: selectionSet
    kind: operation
  kind: document
...
```

Imagine that we have argument of boolean type. We make a typo - write "False" instead of "false". Parser consider it as "enum", not boolean. Finally we don't have an error - after processing we have "true" boolean value.

From [spec](https://spec.graphql.org/draft/#sec-Boolean):
> Input Coercion
When expected as an input type, only boolean input values are accepted. All other input values must raise a request error indicating an incorrect type.

**Comment by Totktonada** [comment]
It seems, it is the regression from 84e9cce88e033c232c3d80e0c2bf650e8b8c7a72.
