### ISSUE TITLE
Add graphql_version constant to make possible to determine module version in runtime

### ISSUE THREAD

**Issue by no1seman** [tarantool/graphql#29]

**Comment by Totktonada** [comment]
Good idea. Usually it is accessible as `require('foo').VERSION`.

**Comment by no1seman** [comment]
Why not require('foo').VeRsIoN or require('foo').vErSiOn?

**Comment by Totktonada** [comment]
Yaroslav's [solution](https://github.com/tarantool/graphqlide/blob/ce1f0c83c45f2e904c999121d5a56376f88d9ed6/.github/workflows/publish.yaml#L37).

**Comment by Totktonada** [comment]
NB: There are [problems](https://github.com/tarantool/graphql/pull/46#issuecomment-1086357159) in the implemented solution.
