### ISSUE TITLE
util.is_array() works inproperly in some cases

### ISSUE THREAD

**Issue by no1seman** [tarantool/graphql#51]
```log
tarantool> g=require('graphql.util')
---
...

tarantool> g.is_array({[3] = 'a', [1] = 'b', [6] = 'c'})
---
- true
...

tarantool> g.is_array({[3] = 'a', [1] = 'b', [7] = 'c'})
---
- false
...

tarantool>
```

**Comment by Totktonada** [comment]
First, don't consider this function as part of the public API of the module. It is literally in the 'graphql util' namespace: utils for implementing the graphql module.

Second, there are different ways to define array in Lua, consider https://github.com/tarantool/tarantool/issues/2765. You may need one or another depending of the task. It is not possible to offer `is_array()` function that will suit all cases.

If something works in an unexpected way in graphql query validations/execution, let us know.

**Comment by Totktonada** [comment]
Closing as invalid.

We're not indend to offer a general purpose `is_array()` function, because it is not possible: someone always will find a case, when it will not be satisfying.
